### ISSUE TITLE
Crazy final bidding after X

### ISSUE THREAD

**Issue by seebrand** [lorserker/ben#147]
A crazy final bidding after  X.  South bids 3c (?), and go 6s . East X , North bid 7s ! Crazy bidding! 
http://127.0.0.1:8080/app/bridge.html?deal=(%27A532.952.AK7.J96%20974.K643.963.AQ5%20KJT86.AQT.2.K432%20Q.J87.QJT854.T87%27,%20%27N%20Both%27)&P=1&board_no=205&S=x&A=x&T=2
![image](https://github.com/user-attachments/assets/1bc2a1d9-eb70-459b-a3ba-15f40c5eafe7)

**Comment by seebrand** [comment]
Another sequence, no 3h,no 7s after X. 
![image](https://github.com/user-attachments/assets/77442eed-9ecc-4335-ad50-0e88fc00bb43)

**Comment by ThorvaldAagaard** [comment]
I get a bit different bidding.

Are you using latest version and default_TF_Short.conf?

**Comment by seebrand** [comment]
I use latest version,and default config. if south is  ben, it gets 4s finally.

**Comment by seebrand** [comment]
sry, it cannot work in TF2_short.  My tensorflow is 2.13.0. 

python gameserver.py --conf config\default_TF2_Short.conf
Playing random deals or deals from the client
Loading tensorflow 2.X
Traceback (most recent call last):
  File "C:\Users\samsung\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\src\saving\serialization_lib.py", line 776, in _retrieve_class_or_fn
    mod = importlib.import_module(module)
  File "C:\Users\samsung\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'keras.src.models.functional'

**Comment by seebrand** [comment]
in default config, does it use PIMC?

**Comment by ThorvaldAagaard** [comment]
Yes, It use PIMC
![image](https://github.com/user-attachments/assets/c128f6bc-9e73-4665-bbba-84e1f69227b1)

**Comment by ThorvaldAagaard** [comment]
This was a nice finding, I have found the error, so after next release BEN will not try to escape the double at next level :-)

**Comment by ThorvaldAagaard** [comment]
BEN no longer bidding this slam, and I will close this, as there is now a check not to run from a double at a higher level in the same suit.
