### ISSUE TITLE
Websocket and tensorflow issue

### ISSUE THREAD

**Issue by michael60045** [lorserker/ben#26]
After following the install instructions in the README.md file, we are having an issue with websockets and errors when tensorflow installed.  Do you have any insight as to why websocket is not working?   Here is a recap of the install and related errors.

We are running the following instance in Amazon's AWS cloud:

Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.1 LTS
Release:	18.04
Codename:	bionic

When starting gameserver.py, the following errors appears, whereas appserver.py starts fine:

(base) ubuntu@ip-xxx-xx-x-xx:~/ben/src$ conda activate ben
(ben) ubuntu@ip-xxx-xx-x-xx:~/ben/src$ python gameserver.py
Traceback (most recent call last):
  File "gameserver.py", line 7, in <module>
    import game
  File "/home/ubuntu/ben/src/game.py", line 12, in <module>
    import bots
  File "/home/ubuntu/ben/src/bots.py", line 8, in <module>
    import nn.player as player
  File "/home/ubuntu/ben/src/nn/player.py", line 2, in <module>
    import tensorflow as tf
ModuleNotFoundError: No module named 'tensorflow'
(ben) ubuntu@ip-1xxx-xx-x-xx:~/ben/src$ python 
Bottle v0.12.23 server starting up (using GeventServer())...
Listening on http://0.0.0.0:8080/
Hit Ctrl-C to quit.

When opening a remote browser, this url works and the "Let's Play" button appears.
http://xx.xxx.xxx.xxx:8080/home

When clicking the "Let's Play" button , this page appears, http://xx.xxx.xxx.xxx:8080/app/bridge.html,  but the page is frozen and the following error is indicated:
"bridge.html:113 WebSocket connection to 'ws://xx.xxx.xxx.xxx:4443/' failed: 
(anonymous) @ bridge.html:113"

**Comment by lorserker** [comment]
hi, from your stacktrace it seems like the main problem is with tensorflow not being available, that's why the gameserver fails to start.
i think that the websocket just errors because there is no connection (to the server which failed to start)

did you get any errors while setting up environment and installing tensorflow?

**Comment by michael60045** [comment]
Hi Lorend,

Thanks for the quick reply.  Yes, tensorflow install was the only one with errors.   Here is an excerpt from my terminal wndow that shows the tensorflow errors:

.........

Successfully installed tqdm-4.64.1

Collecting websockets

  Using cached websockets-10.3-cp37-cp37m-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (112 kB)

Installing collected packages: websockets

Successfully installed websockets-10.3

Collecting tensorflow==1.15

  Downloading tensorflow-1.15.0-cp37-cp37m-manylinux2010_x86_64.whl (412.3 MB)

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸ 412.3/412.3 MB 32.4 MB/s eta 0:00:01

ERROR: Exception:

Traceback (most recent call last):

  File "/home/ubuntu/miniconda3/envs/ben/lib/python3.7/site-packages/pip/_internal/cli/base_command.py", line 167, in exc_logging_wrapper

    status = run_func(*args)

  File "/home/ubuntu/miniconda3/envs/ben/lib/python3.7/site-packages/pip/_internal/cli/req_command.py", line 247, in wrapper

    return func(self, options, args)

  File "/home/ubuntu/miniconda3/envs/ben/lib/python3.7/site-packages/pip/_internal/commands/install.py", line 370, in run

    reqs, check_supported_wheels=not options.target_dir

  File "/home/ubuntu/miniconda3/envs/ben/lib/python3.7/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 93, in resolve

    collected.requirements, max_rounds=try_to_avoid_resolution_too_deep

  File "/home/ubuntu/miniconda3/envs/ben/lib/python3.7/site-packages/pip/_vendor/resolvelib/resolvers.py", line 481, in resolve

    state = resolution.resolve(requirements, max_rounds=max_rounds)

  File "/home/ubuntu/miniconda3/envs/ben/lib/python3.7/site-packages/pip/_vendor/resolvelib/resolvers.py", line 348, in resolve

    self._add_to_criteria(self.state.criteria, r, parent=None)

  File "/home/ubuntu/miniconda3/envs/ben/lib/python3.7/site-packages/pip/_vendor/resolvelib/resolvers.py", line 172, in _add_to_criteria

    if not criterion.candidates:

  File "/home/ubuntu/miniconda3/envs/ben/lib/python3.7/site-packages/pip/_vendor/resolvelib/structs.py", line 151, in __bool__

    return bool(self._sequence)

  File "/home/ubuntu/miniconda3/envs/ben/lib/python3.7/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 155, in __bool__

    return any(self)

  File "/home/ubuntu/miniconda3/envs/ben/lib/python3.7/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 143, in <genexpr>

    return (c for c in iterator if id(c) not in self._incompatible_ids)

  File "/home/ubuntu/miniconda3/envs/ben/lib/python3.7/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 47, in _iter_built

    candidate = func()

  File "/home/ubuntu/miniconda3/envs/ben/lib/python3.7/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 211, in _make_candidate_from_link

    version=version,

  File "/home/ubuntu/miniconda3/envs/ben/lib/python3.7/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 303, in __init__

    version=version,

  File "/home/ubuntu/miniconda3/envs/ben/lib/python3.7/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 162, in __init__

    self.dist = self._prepare()

  File "/home/ubuntu/miniconda3/envs/ben/lib/python3.7/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 231, in _prepare

    dist = self._prepare_distribution()

  File "/home/ubuntu/miniconda3/envs/ben/lib/python3.7/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 308, in _prepare_distribution

    return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True)

  File "/home/ubuntu/miniconda3/envs/ben/lib/python3.7/site-packages/pip/_internal/operations/prepare.py", line 438, in prepare_linked_requirement

    return self._prepare_linked_requirement(req, parallel_builds)

  File "/home/ubuntu/miniconda3/envs/ben/lib/python3.7/site-packages/pip/_internal/operations/prepare.py", line 489, in _prepare_linked_requirement

    hashes,

  File "/home/ubuntu/miniconda3/envs/ben/lib/python3.7/site-packages/pip/_internal/operations/prepare.py", line 169, in unpack_url

    hashes=hashes,

  File "/home/ubuntu/miniconda3/envs/ben/lib/python3.7/site-packages/pip/_internal/operations/prepare.py", line 106, in get_http_url

    from_path, content_type = download(link, temp_dir.path)

  File "/home/ubuntu/miniconda3/envs/ben/lib/python3.7/site-packages/pip/_internal/network/download.py", line 147, in __call__

    for chunk in chunks:

  File "/home/ubuntu/miniconda3/envs/ben/lib/python3.7/site-packages/pip/_internal/cli/progress_bars.py", line 53, in _rich_progress_bar

    for chunk in iterable:

  File "/home/ubuntu/miniconda3/envs/ben/lib/python3.7/site-packages/pip/_internal/network/utils.py", line 87, in response_chunks

    decode_content=False,

  File "/home/ubuntu/miniconda3/envs/ben/lib/python3.7/site-packages/pip/_vendor/urllib3/response.py", line 573, in stream

    data = self.read(amt=amt, decode_content=decode_content)

  File "/home/ubuntu/miniconda3/envs/ben/lib/python3.7/site-packages/pip/_vendor/urllib3/response.py", line 516, in read

    data = self._fp.read(amt) if not fp_closed else b""

  File "/home/ubuntu/miniconda3/envs/ben/lib/python3.7/site-packages/pip/_vendor/cachecontrol/filewrapper.py", line 96, in read

    self._close()

  File "/home/ubuntu/miniconda3/envs/ben/lib/python3.7/site-packages/pip/_vendor/cachecontrol/filewrapper.py", line 76, in _close

    self.__callback(result)

  File "/home/ubuntu/miniconda3/envs/ben/lib/python3.7/site-packages/pip/_vendor/cachecontrol/controller.py", line 353, in cache_response

    self._cache_set(cache_url, request, response, body, expires_time)

  File "/home/ubuntu/miniconda3/envs/ben/lib/python3.7/site-packages/pip/_vendor/cachecontrol/controller.py", line 274, in _cache_set

    self.serializer.dumps(request, response, body),

  File "/home/ubuntu/miniconda3/envs/ben/lib/python3.7/site-packages/pip/_vendor/cachecontrol/serialize.py", line 70, in dumps

    return b",".join([b"cc=4", msgpack.dumps(data, use_bin_type=True)])

MemoryError

Collecting grpcio-tools

  Using cached grpcio_tools-1.50.0-cp37-cp37m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (2.4 MB)

Collecting grpcio>=1.50.0

  Using cached grpcio-1.50.0-cp37-cp37m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (4.7 MB)

Requirement already satisfied: setuptools in /home/ubuntu/miniconda3/envs/ben/lib/python3.7/site-packages (from grpcio-tools) (63.4.1)

Collecting protobuf<5.0dev,>=4.21.6

  Using cached protobuf-4.21.8-cp37-abi3-manylinux2014_x86_64.whl (408 kB)

Requirement already satisfied: six>=1.5.2 in /home/ubuntu/miniconda3/envs/ben/lib/python3.7/site-packages (from grpcio>=1.50.0->grpcio-tools) (1.16.0)

Installing collected packages: protobuf, grpcio, grpcio-tools

Successfully installed grpcio-1.50........

Thanks so much for looking into this.
Michael Lollino

________________________________

**Comment by michael60045** [comment]
On the "Amazon Linux 2 AMI" Amazon aws instance,  I got tensorflow to install and needed to downgrade protobuf to get gamerserver.py to start.

**Comment by lorserker** [comment]
i'm glad you made it work.
