### ISSUE TITLE
AssertionError: No samples for DDSolver

### ISSUE THREAD

**Issue by ataylorappt** [lorserker/ben#84]
Hello again, i am getting the below error when playing a game with the bots in docker, how can I resolve this?

```
Playing random deals or deals from the client
models loaded
Listening on port:  4443
Got websocket connection
Setting seed=42
Setting seed (Full deal)= 1490532987
Deal: ('AQT974.862..K532 8.753.AQJ87.J976 K32.AJ4.9532.AT4 J65.KQT9.KT64.Q8', 'S Both')
{"message": "deal_start", "dealer": 2, "vuln": [true, true], "hand": "K32.AJ4.9532.AT4"}
{"message": "bid_made", "auction": ["PAD_START", "PAD_START", "2H"]}
{"message": "bid_made", "auction": ["PAD_START", "PAD_START", "2H", "PASS"]}
{"message": "bid_made", "auction": ["PAD_START", "PAD_START", "2H", "PASS", "4H"]}
{"message": "bid_made", "auction": ["PAD_START", "PAD_START", "2H", "PASS", "4H", "PASS"]}
{"message": "bid_made", "auction": ["PAD_START", "PAD_START", "2H", "PASS", "4H", "PASS", "4S"]}
{"message": "bid_made", "auction": ["PAD_START", "PAD_START", "2H", "PASS", "4H", "PASS", "4S", "PASS"]}
{"message": "bid_made", "auction": ["PAD_START", "PAD_START", "2H", "PASS", "4H", "PASS", "4S", "PASS", "PASS"]}
{"message": "bid_made", "auction": ["PAD_START", "PAD_START", "2H", "PASS", "4H", "PASS", "4S", "PASS", "PASS", "PASS"]}
{"message": "auction_end", "declarer": 2, "auction": ["PAD_START", "PAD_START", "2H", "PASS", "4H", "PASS", "4S", "PASS", "PASS", "PASS"], "strain": 1}
trick 1
Setting seed (Opening lead)= 1490532987
{"message": "card_played", "player": 3, "card": "S6"}
{"message": "show_dummy", "player": 3, "dummy": "AQT974.862..K532"}
Loaded lib libdds.so
{"message": "card_played", "player": 0, "card": "S7"}
{"message": "card_played", "player": 1, "card": "S8"}
{"message": "card_played", "player": 2, "card": "S2"}
Trick confirm: y
trick 2
{"message": "card_played", "player": 1, "card": "C7"}
{"message": "card_played", "player": 2, "card": "CA"}
{"message": "card_played", "player": 3, "card": "C8"}
{"message": "card_played", "player": 0, "card": "C5"}
Trick confirm: y
trick 3
{"message": "card_played", "player": 2, "card": "H4"}
{"message": "card_played", "player": 3, "card": "H9"}
{"message": "card_played", "player": 0, "card": "H6"}
{"message": "card_played", "player": 1, "card": "H3"}
Trick confirm: y
trick 4
{"message": "card_played", "player": 3, "card": "HK"}
{"message": "card_played", "player": 0, "card": "H8"}
{"message": "card_played", "player": 1, "card": "H5"}
{"message": "card_played", "player": 2, "card": "HA"}
Trick confirm: y
trick 5
{"message": "card_played", "player": 2, "card": "CT"}
{"message": "card_played", "player": 3, "card": "CQ"}
{"message": "card_played", "player": 0, "card": "CK"}
{"message": "card_played", "player": 1, "card": "C6"}
Trick confirm: y
trick 6
{"message": "card_played", "player": 0, "card": "H2"}
{"message": "card_played", "player": 1, "card": "H7"}
{"message": "card_played", "player": 2, "card": "HJ"}
{"message": "card_played", "player": 3, "card": "HQ"}
Trick confirm: y
trick 7
{"message": "card_played", "player": 3, "card": "S5"}
{"message": "card_played", "player": 0, "card": "SA"}
{"message": "card_played", "player": 1, "card": "D7"}
{"message": "card_played", "player": 2, "card": "SK"}
Trick confirm: y
trick 8
{"message": "card_played", "player": 0, "card": "SQ"}
Error: No samples for DDSolver
connection handler failed
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/websockets/legacy/server.py", line 236, in handler
    await self.ws_handler(self)
  File "/usr/local/lib/python3.10/dist-packages/websockets/legacy/server.py", line 1175, in _ws_handler
    return await cast(
  File "/app/src/gameserver.py", line 186, in handler
    raise ex
  File "/app/src/gameserver.py", line 169, in handler
    await driver.run()
  File "/app/src/game.py", line 171, in run
    await self.play(auction, opening_lead52)
  File "/app/src/game.py", line 277, in play
    card_resp = await card_players[player_i].async_play_card(trick_i, leader_i, current_trick52, rollout_states)
  File "/app/src/game.py", line 62, in async_play_card
    return self.play_card(trick_i, leader_i, current_trick52, players_states)
  File "/app/src/bots.py", line 589, in play_card
    card52_dd = self.next_card52(trick_i, leader_i, current_trick52, players_states)
  File "/app/src/bots.py", line 598, in next_card52
    assert n_samples > 0, "No samples for DDSolver"
AssertionError: No samples for DDSolver
```

Thanks in advance

**Comment by ThorvaldAagaard** [comment]
It found no samples to match - I will check and return. First time I have seen it so late in the play

**Comment by ataylorappt** [comment]
Yeah i am south, i also just hit pass for every bid

**Comment by ThorvaldAagaard** [comment]
This should be solved now, please check and close this issue if you agree.
